# Generated by Django 5.2.3 on 2025-07-27 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('star_rating', models.CharField(choices=[('★★★★★', 'Excellent - ★★★★★'), ('★★★★☆', 'Good - ★★★★☆'), ('★★★☆☆', 'Average - ★★★☆☆'), ('★★☆☆☆', 'Poor - ★★☆☆☆'), ('★☆☆☆☆', 'Terrible - ★☆☆☆☆'), ('', 'Choose your rating...')], default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.productmodel')),
            ],
        ),
    ]
