# Generated by Django 5.2.3 on 2025-07-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('star_rating', models.CharField(choices=[('★★★★★', 'Excellent'), ('★★★★☆', 'Good'), ('★★★☆☆', 'Average'), ('★★☆☆☆', 'Poor'), ('★☆☆☆☆', 'Terrible'), ('choose your rating...', 'Choose your rating...')], default='choose your rating...')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reviews', to='accounts.accountmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.productmodel')),
            ],
        ),
    ]
