# Generated by Django 5.2.3 on 2025-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='star_rating',
            field=models.CharField(choices=[('★★★★★', 'Excellent - ★★★★★'), ('★★★★☆', 'Good - ★★★★☆'), ('★★★☆☆', 'Average - ★★★☆☆'), ('★★☆☆☆', 'Poor - ★★☆☆☆'), ('★☆☆☆☆', 'Terrible - ★☆☆☆☆'), ('', 'Choose your rating...')], default=''),
        ),
    ]
