# Generated by Django 5.2.3 on 2025-07-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_remove_productmodel_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsproductsmodel',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizemodel'),
        ),
    ]
