# Generated by Django 5.2.3 on 2025-07-23 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productmodel_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(default='Sofia', max_length=100)),
                ('country', models.CharField(default='България', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_method', models.CharField(choices=[('econt', 'Econt'), ('sameday_easybox', 'Sameday Easybox'), ('sameday_address', 'Sameday to address')], max_length=20)),
                ('econt_office_code', models.CharField(blank=True, max_length=100, null=True)),
                ('econt_office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('econt_office_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='products.productmodel')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.ordermodel')),
            ],
        ),
    ]
