# Generated by Django 5.2.3 on 2025-07-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
