# Generated by Django 5.2.3 on 2025-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordermodel_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='econt_office_code',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='econt_office_name',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='econt_office_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
