# Generated by Django 5.2.3 on 2025-07-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='available',
        ),
    ]
